### PR TITLE
Create index.html

### PR DESCRIPTION
**Pull request by yesbhautik**

### CODE REVIEW

**Comment by Kugelschieber** [comment]
Did you use an AI to create this PR? Just curious, because it doesn't make sense at all to merge this into our custom website solution (Shifu) :smile:

**Comment by yesbhautik** [comment]
> Did you use an AI to create this PR? Just curious, because it doesn't make any sense at all to merge this into our custom website solution (Shifu) 😄

without index file how this website will work? I created this PR byself only.

**Comment by Kugelschieber** [comment]
We've created a custom CMS based on Go template files and JSON. You can go and check it out if you like:

https://github.com/emvi/shifu

**Comment by yesbhautik** [comment]
> We've created a custom CMS based on Go template files and JSON. You can go and check it out if you like:
> 
> https://github.com/emvi/shifu

Sorry my bad, I just pressed ctrl U of this repo website, and inserted to repo because the main index file is missing...

can you please provide the original file to run this website as in repo?

**Comment by Motorschpocht** [comment]
Why?

**Comment by yesbhautik** [comment]
> Why?

It's open-source, anyone can run it. It is based on your Custom CMS, so to look into or deploy or contribute, we just have to know how to run this along with your Custom CMS.

At least provide the docs/Instructions to run the website smoothly.

**Comment by Kugelschieber** [comment]
Sure, but please don't copy our design. We had a case like this in the past.

1. Compile the latest version of Shifu (0.9) using Go
2. Clone this repo
3. Create the configuration (https://github.com/emvi/shifu?tab=readme-ov-file#configuration)
4. Start Shifu inside the main directory `shifu`
5. Open it in your browser on localhost

**Comment by yesbhautik** [comment]
image
🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️

**Comment by Kugelschieber** [comment]
```
git clone https://github.com/emvi/shifu.git
cd shifu
make build_linux
chmod +x shifu
sudo mv shifu /usr/local/bin
```

**Comment by yesbhautik** [comment]
```cmd
root@testZone:~# git clone https://github.com/emvi/shifu
Cloning into 'shifu'...
remote: Enumerating objects: 1645, done.
remote: Counting objects: 100% (95/95), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 1645 (delta 26), reused 34 (delta 11), pack-reused 1550 (from 1)
Receiving objects: 100% (1645/1645), 3.47 MiB | 14.92 MiB/s, done.
Resolving deltas: 100% (625/625), done.
root@testZone:~# rm -rf -f /usr/local/bin/shifu/
root@testZone:~# cd shifu
root@testZone:~/shifu# make build_linux
go test -cover ./pkg/...
go: errors parsing go.mod:
/root/shifu/go.mod:3: invalid go version '1.23.2': must match format 1.23
make: *** [Makefile:11: test] Error 1
root@testZone:~/shifu# nano go.mod 
root@testZone:~/shifu# make build_linux
go test -cover ./pkg/...
pkg/cfg/config.go:9:2: cannot find package "." in:
        /root/shifu/vendor/log/slog
pkg/cms/funcmap.go:13:2: cannot find package "." in:
        /root/shifu/vendor/math/rand/v2
pkg/cms/cms.go:20:2: cannot find package "." in:
        /root/shifu/vendor/slices
make: *** [Makefile:11: test] Error 1
root@testZone:~/shifu# 
```

**Comment by yesbhautik** [comment]
> make build_linux

Another try

```cmd
root@testZone:~# gvm install go1.23.2 -B
Installing go1.23.2 from binary source
root@testZone:~# gvm use go1.23.2 --default
Now using version go1.23.2
root@testZone:~# go version
go version go1.23.2 linux/amd64
root@testZone:~# cd shifu/^C
root@testZone:~# rm -rf -f shifu/
root@testZone:~# git clone https://github.com/emvi/shifu.git
Cloning into 'shifu'...
remote: Enumerating objects: 1645, done.
remote: Counting objects: 100% (95/95), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 1645 (delta 26), reused 34 (delta 11), pack-reused 1550 (from 1)
Receiving objects: 100% (1645/1645), 3.47 MiB | 12.78 MiB/s, done.
Resolving deltas: 100% (625/625), done.
root@testZone:~# cd shifu
root@testZone:~/shifu# make build_linux
go test -cover ./pkg/...
        github.com/emvi/shifu/pkg               coverage: 0.0% of statements
ok      github.com/emvi/shifu/pkg/analytics     0.005s  coverage: 53.1% of statements
ok      github.com/emvi/shifu/pkg/cfg   0.102s  coverage: 67.5% of statements
ok      github.com/emvi/shifu/pkg/cms   0.033s  coverage: 17.5% of statements
        github.com/emvi/shifu/pkg/middleware            coverage: 0.0% of statements
ok      github.com/emvi/shifu/pkg/js    0.063s  coverage: 72.7% of statements
        github.com/emvi/shifu/pkg/source                coverage: 0.0% of statements
2024/10/20 20:58:03 INFO Compiling sass file in=in/test.scss out=out/test.css
2024/10/20 20:58:03 ERROR Error compiling sass error="exec: \"sass\": executable file not found in $PATH"
--- FAIL: TestCompileSass (0.10s)
    sass_test.go:30: 
                Error Trace:    /root/shifu/pkg/sass/sass_test.go:30
                Error:          unable to find file "out/test.css"
                Test:           TestCompileSass
    sass_test.go:31: 
                Error Trace:    /root/shifu/pkg/sass/sass_test.go:31
                Error:          unable to find file "out/test.css.map"
                Test:           TestCompileSass
    sass_test.go:33: 
                Error Trace:    /root/shifu/pkg/sass/sass_test.go:33
                Error:          Received unexpected error:
                                open out/test.css: no such file or directory
                Test:           TestCompileSass
    sass_test.go:34: 
                Error Trace:    /root/shifu/pkg/sass/sass_test.go:34
                Error:          "" does not contain ".class-name{color:red}"
                Test:           TestCompileSass
2024/10/20 20:58:03 INFO Compiling sass file in=in/test.scss out=out/test.css
2024/10/20 20:58:03 ERROR Error compiling sass error="exec: \"sass\": executable file not found in $PATH"
2024/10/20 20:58:03 INFO Compiling sass file in=in/test.scss out=out/test.css
2024/10/20 20:58:03 ERROR Error compiling sass error="exec: \"sass\": executable file not found in $PATH"
2024/10/20 20:58:03 INFO Compiling sass file in=in/test.scss out=out/test.css
2024/10/20 20:58:03 ERROR Error compiling sass error="exec: \"sass\": executable file not found in $PATH"
--- FAIL: TestWatchSass (1.20s)
    sass_test.go:51: 
                Error Trace:    /root/shifu/pkg/sass/sass_test.go:51
                Error:          unable to find file "out/test.css"
                Test:           TestWatchSass
    sass_test.go:53: 
                Error Trace:    /root/shifu/pkg/sass/sass_test.go:53
                Error:          Received unexpected error:
                                open out/test.css: no such file or directory
                Test:           TestWatchSass
    sass_test.go:54: 
                Error Trace:    /root/shifu/pkg/sass/sass_test.go:54
                Error:          "" does not contain ".class-name{color:red}"
                Test:           TestWatchSass
    sass_test.go:57: 
                Error Trace:    /root/shifu/pkg/sass/sass_test.go:57
                Error:          unable to find file "out/test.css"
                Test:           TestWatchSass
    sass_test.go:59: 
                Error Trace:    /root/shifu/pkg/sass/sass_test.go:59
                Error:          Received unexpected error:
                                open out/test.css: no such file or directory
                Test:           TestWatchSass
    sass_test.go:60: 
                Error Trace:    /root/shifu/pkg/sass/sass_test.go:60
                Error:          "" does not contain ".class-name{color:blue}"
                Test:           TestWatchSass
FAIL
coverage: 79.6% of statements
FAIL    github.com/emvi/shifu/pkg/sass  1.309s
ok      github.com/emvi/shifu/pkg/sitemap       0.011s  coverage: 31.0% of statements
FAIL
make: *** [Makefile:11: test] Error 1
root@testZone:~/shifu# 
```

**Comment by yesbhautik** [comment]
Finally, Done.

```cmd
sudo apt-get install bison
bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
gvm install go1.23.2 -B
gvm use go1.23.2 --default
****insatall nodejs/npm
npm install -g sass
git clone https://github.com/emvi/shifu.git
cd shifu
make build_linux
chmod +x shifu
sudo mv shifu /usr/local/bin
shifu version

Request to maintainer: Please, update the proper docs, alos publish the direct packages (arm64 amd both) if possible.
I am happy to contribute if there is any roadmap finalized OR we can discuss about it.

**Comment by yesbhautik** [comment]
> Sure, but please don't copy our design. We had a case like this in the past.
> 
> 1. Compile the latest version of Shifu (0.9) using Go
> 2. Clone this repo
> 3. Create the configuration (https://github.com/emvi/shifu?tab=readme-ov-file#configuration)
> 4. Start Shifu inside the main directory `shifu`
> 5. Open it in your browser on localhost

image
Help, here please.

**Comment by yesbhautik** [comment]
> Sure, but please don't copy our design. We had a case like this in the past.
> 
> 1. Compile the latest version of Shifu (0.9) using Go
> 2. Clone this repo
> 3. Create the configuration (https://github.com/emvi/shifu?tab=readme-ov-file#configuration)
> 4. Start Shifu inside the main directory `shifu`
> 5. Open it in your browser on localhost

image
Now help...
*I also tried with my port forwarding to my domain

**Comment by yesbhautik** [comment]
I am out, tried a lot... @Motorschpocht if you can help me personally, it will be very good. thanks. I already given a lot of hours on it.

**Comment by Kugelschieber** [comment]
We have created a few custom handlers that are not part of Shifu, so you need to remove them. Go through the logs and remove all function calls from the template files ("validation" in discourse.html for example).

Btw. we also sell websites and offer dev services if you're interested: https://emvi.com

**Comment by yesbhautik** [comment]
> discourse.html

Just help me to start the website on my device/server, that is set. I am not able to figure out this Go stuff.

**Comment by yesbhautik** [comment]
@Motorschpocht I am waiting, brother.
https://links.yesbhautik.co.in/ ping me wherever you wish.

**Pull request closed without merging**
